version: 3.9

services:
  db:
    container_name: db
    image: "mysql:5.7.33"
    command: "--default-authentication-plugin=mysql_native_password"
    volumes: # Ephemeral volume mounting issue and double-init: https://github.com/docker-library/mysql/issues/395#issuecomment-375409393
      - db-datavolume:/var/lib/mysql
      - ./sql/1.sql:/docker-entrypoint-initdb.d/1.sql
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "httpstreampoc"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "pw123"

volumes:
  db-datavolume:
